[colors.primary]
# Henna Dark Alacritty Color Scheme
background = "#21272e"
foreground = "#f8f8f0"

# Normal colors
[colors.normal]
black   = "#21272e"
red     = "#e74c3c"
green   = "#53df83"
yellow  = "#9cd230"
blue    = "#1abc9c"
magenta = "#e74c3c"
cyan    = "#1abc9c"
white   = "#f8f8f0"

# Bright colors
[colors.bright]
black   = "#181A1F"
red     = "#e74c3c"
green   = "#53df83"
yellow  = "#9cd230"
blue    = "#1abc9c"
magenta = "#e74c3c"
cyan    = "#1abc9c"
white   = "#f8f8f0"

# Cursor colors
[colors.cursor]
text    = "#21272e"
cursor  = "#1abc9c"