keys:
  - &admin_m32 DE0FE946DDA34B3BD1F92D59E017B967AC29E321
  - &host_phoenix age1wnxruyg2pvwcmfuqfqy0r4s7u39y98jpma7rkt26hguxu5pfj5eqx687f3
creation_rules:
  - path_regex: secrets/[^/]+\.yml$
    key_groups:
    - pgp:
        - *admin_m32_pgp
  - path_regex: modules/users/[^/]+\.yml$
    key_groups:
    - pgp:
      - *admin_m32
  - path_regex: modules/hosts/phoenix\.yml$
    key_groups:
    - pgp:
      - *admin_m32
      age:
      - *host_phoenix
