on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 */7 * *'
jobs:
  update:
    name: Update flake input lockfile
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v3
      - name: Install Nix
        id: install-nix
        uses: cachix/install-nix-action@v30
      - name: Run Flake Update
        id: flake-update
        run: "nix flake update 2> actions_changes.txt"
      - name: Create Pull Request
        id: pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: actions/auto-update
          title: "flake: update flake inputs"
          commit-message: "ci(flake): automatic lock update"
          signoff: true
          sign-commits: true
          body-path: actions_changes.txt
          reviewers: notm32
          assignees: notm32
